### ISSUE TITLE
ss://格式被加密了两次

### ISSUE THREAD

**Issue by Sostay** [juerson/config_to_sub#3]
![图片](https://github.com/user-attachments/assets/ffcf7092-dfe5-41db-ad97-5129f03e7787)
clash meta 无法正常使用

**Comment by Sostay** [comment]
![图片](https://github.com/user-attachments/assets/ffcf7092-dfe5-41db-ad97-5129f03e7787)
clash meta 无法正常使用

**Comment by juerson** [comment]
电脑不在身边，无法判断是那个问题，记得，是两次Base64加密，第一次加密是构成分享链接（加密关键参数，比如服务器的地址和端口，以及密码），第二次加密是将所有转换后的分享链接base64加密，避免直接显得ss://、vless://、trojan://...等。

就你截图的信息，转换为clash会不会有字段出错https://clash.wiki/configuration/outbound.html#shadowsocks、https://wiki.metacubex.one/config/proxies/，看这里对照一下。

提醒一下，clash的配置，name字段值可能因没有引号，其值有“:”冒号报错（其他字段对应的值一样）。

有时间过年回去再看看代码，代码写了很久就不用了，感觉共享的订阅，其节点地址比较脏，当成备用使用。

**Comment by Sostay** [comment]
用sub store转换 订阅链接会被识别为 ss://加密协议 
（里面个别节点还可以 所以一直在用😃

**Comment by Sostay** [comment]
https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml
找出来了 是这个订阅的问题，把这个删了就正常了~
